### ISSUE TITLE
Problematic /etc/hosts file entry in provisioned VM

### ISSUE THREAD

**Issue by pschiffe** [purpleidea/oh-my-vagrant#114]
When I provision VM with oh-my-vagrant, I see this `/etc/hosts` file in provisioned VM:
```
[vagrant@omv1 ~]$ cat /etc/hosts
127.0.0.1   omv1 localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

## vagrant-hostmanager-start
192.168.123.100	omv1

## vagrant-hostmanager-end
```

Problematic line is:
```
127.0.0.1   omv1 localhost localhost.localdomain localhost4 localhost4.localdomain4
```

Hostname can't resolve to `127.0.0.1` IP address. This can cause problems for various daemons resolving hostname and taking `127.0.0.1` as their IP, where it should be, in this case, `192.168.123.100`. Correct `/etc/hosts` file in this case should be:
```
[vagrant@omv1 ~]$ cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

## vagrant-hostmanager-start
192.168.123.100	omv1

## vagrant-hostmanager-end
```

I'm willing to create patch for this issue, but I wasn't able to identify what is responsible for this setting. Could you help me with this?

**Comment by purpleidea** [comment]
@pschiffe The /etc/hosts automagic happens in this section:

https://github.com/purpleidea/oh-my-vagrant/blob/master/vagrant/Vagrantfile#L835

It uses a modified version of the hostmanager plugin, since the upstream isn't very responsive.
https://github.com/purpleidea/vagrant-hostmanager/tree/feat/extras

In fact, I'd have to look through this code, but you might be interested in what happens here:

https://github.com/purpleidea/vagrant-hostmanager/commit/f087051398d567592535496f811a9b0447190d0b

But you'd have to provide a but more info into what's breaking because I'm still too sleepy to think about DNS issues atm ;)

Cheers!

**Comment by pschiffe** [comment]
@purpleidea Ah! So this is fixed in the patched version of vagrant-hostmanager. I'm being amateur was using unmodified version of this plugin. Thanks!

But now I see another curious line in the `/etc/hosts` file:
```
[vagrant@omv1 ~]$ cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

## vagrant-hostmanager-start
192.168.124.100	omv1.example3.com	omv1
192.168.124.3	omv.example3.com	omv
## vagrant-hostmanager-end
```

I'm using like most basic `omv.yaml` file, but I don't know what is the `192.168.124.3	omv.example3.com	omv` line?

**Comment by purpleidea** [comment]
@pschiffe No problem :)

The extra line is a bonus "DNS" entry for a VIP when needed by the cluster... It turns out it's convenient to have that from time to time, so it's a little developer bonus. Since it doesn't usually hurt to have it there, you get it for free... Want to write an FAQ item about it? https://github.com/purpleidea/oh-my-vagrant/blob/master/DOCUMENTATION.md#usage-and-frequently-asked-questions

Cheers,
James

**Comment by pschiffe** [comment]
I see, thanks.

**Comment by purpleidea** [comment]
Want to write an FAQ item about it?

**Comment by pschiffe** [comment]
I still don't understand it properly. I get that it's not a bug, but that's all. I don't know what VIP means, where it points to and what uses it..

**Comment by purpleidea** [comment]
On Mon, Aug 24, 2015 at 8:02 AM, Peter Schiffer <notifications@github.com>
wrote:

> I still don't understand it properly. I get that it's not a bug, but
> that's all. I don't know what VIP means, where it points to and what uses
> it..



VIP means virtual ip. It's an extra IP that is reserved on each host, by
default unused, comes with DNS via /etc/hosts and can be used by the
developer for any purpose they want. That's all.
